version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - g-guirado
  ignore:
  - dependency-name: dateformat
    versions:
    - 4.5.0
